### ISSUE TITLE
can load config from directory?

### ISSUE THREAD

**Issue by sangeren** [georg-jung/FastBertTokenizer#34]
can implement like this：

AutoTokenizer.from_pretrained("test")

form a  director 。

thanks

**Comment by georg-jung** [comment]
Hugging Face's `from_pretrained` [supports many different kinds of inputs](https://huggingface.co/docs/transformers/model_doc/auto#transformers.AutoConfig.from_pretrained), e.g.:

* A Hugging Face model id, e.g. `from_pretrained("bert-base-cased")` which then downloads and caches the configuration from the online Hugging Face repo
* A local path to a directory, e.g. `from_pretrained("./my_model_directory/")`
* A local path to a configuration file, e.g. `from_pretrained("./my_model_directory/configuration.json")`

Thus, if you write `AutoTokenizer.from_pretrained("test")` you will not actually load files from a directory but rather from an online Hugging Face repository.

Version `0.3.29` of FastBertTokenizer - that is currently available on NuGet - only supports loading local `vocab.txt` files like described in the README:

```csharp
var tok = new BertTokenizer();
await tok.LoadVocabularyAsync("/local/path/to/vocab.txt", true);
```

`vocab.txt` and `tokenizer.json` are two different formats to describe the vocabulary of a tokenizer. You can convert the vocabulary from a `tokenizer.json` file to a `vocab.txt` file.

The next release of `FastBertTokenizer` (which will probably be published in some days) will support more vocabulary loading options:

```csharp
var tok = new BertTokenizer();
await tok.LoadVocabularyAsync("/local/path/to/vocab.txt", true);
await tok.LoadTokenizerJsonAsync("/local/path/to/tokenizer.json");
await tok.LoadFromHuggingFaceAsync("baert-bvase-uncased"); // downloads from Hugging Face online repository
```

In the meantime, your best option is to download an existing vocab.txt file for the model you want to use and load it like described in the readme, specifying it's full path.
